#!/usr/bin/perl

$home = $ENV{HOME};
$pwd = "$home/.config/dwm";

chdir $pwd;

system "make";

chdir $home;

#if (fork == 0) {
#    sleep 1
#    `feh --bg-fill $HOME/Images/Wallpapers/current.*`;
#}

exec "$pwd/dwm";
